version: "3"
services:
  calendar:
    container_name: frontEnd
    restart: always
    build:
      context: ./client/calendar
      dockerfile: DOCKERFILE
    ports:
      - "80:3000"
    volumes:
      - .:/calendar
  
