version: "3"
services:
  server:
    container_name: backEnd
    restart: always
    build:
      context: ./server
      dockerfile: DOCKERFILE
    ports:
      - "5000:5000"
    volumes:
      - .:/server
  calendar:
    container_name: frontEnd
    restart: always
    build:
      context: ./client/calendar
      dockerfile: DOCKERFILE
    ports:
      - "80:3000"
    volumes:
      - .:/calendar

  
